language: node_js
sudo: false
node_js:
  - "10.8.0"
cache:
  directories:
    - "node_modules"
before_install:
  # - npm i -g serverless
install:
  - npm i
script:
  - npm run test
  - npm run report:coverage
  # - sls deploy
